#ifndef CONSTANTS_H
#define CONSTANTS_H

#define DEBUG 1

#define MAX_NAME_LEN 50
#define MAX_WEAPON_NAME_LEN 50

// Character Constants
#define CHARACTER_HEALTH 100
#define CHARACTER_HEALTH_RETURN 0
#define CHARACTER_POINT_VALUE 0
#define BARBARIAN_ATTACK 13
#define BARBARIAN_DEFENSE 10
#define BARBARIAN_WEAPON "Axe"
#define WIZARD_ATTACK 10
#define WIZARD_DEFENSE 13
#define WIZARD_WEAPON "Magic Missle"

// Enemy Character Constants
#define SLIME_HEALTH 10
#define SLIME_ATTACK 5
#define SLIME_DEFENSE 2
#define SLIME_WEAPON "Acid Spit"
#define SLIME_HEALTH_RETURN 5
#define SLIME_POINT_VALUE 5

#define SKELETON_HEALTH 20
#define SKELETON_ATTACK 10
#define SKELETON_DEFENSE 9
#define SKELETON_WEAPON "Sword"
#define SKELETON_HEALTH_RETURN 15
#define SKELETON_POINT_VALUE 20

#define ENDBOSS_HEALTH 150
#define ENDBOSS_ATTACK 20
#define ENDBOSS_DEFENSE 15
#define ENDBOSS_WEAPON "Great Sword"
#define ENDBOSS_HEALTH_RETURN 50
#define ENDBOSS_POINT_VALUE 100
#endif //CONSTANTS_H
